### ISSUE TITLE
[BUG] java.lang.IllegalArgumentException: syntax error, expected column name

### ISSUE THREAD

**Issue by Kita2345** [RocketScientists/Rocket#57]
java.lang.IllegalArgumentException: syntax error, expected column name
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:167)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:420)
	at android.content.ContentResolver.query(ContentResolver.java:478)
	at android.content.ContentResolver.query(ContentResolver.java:422)
	at android.app.DownloadManager$Query.runQuery(DownloadManager.java:904)
	at android.app.DownloadManager.query(DownloadManager.java:1010)
	at org.mozilla.rocket.download.data.AndroidDownloadManagerDataSource$getDownloadingItems$2.invokeSuspend(AndroidDownloadManagerDataSource.kt:133)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by Kita2345** [comment]
downloading from https://www.bbk.bund.de/DE/Warnung-Vorsorge/Warn-App-NINA/NINA-Download/nina-download_node.html causes crash

**Comment by walkingice** [comment]
thank you for reporting this. The apk you used, is that built from this repository?

**Comment by Kita2345** [comment]
i use your app which comes from play store

**Comment by walkingice** [comment]
<img width="839" alt="Screen Shot 2021-08-14 at 22 41 50" src="https://user-images.githubusercontent.com/54793/129448189-4e821a80-2193-4c94-88e2-1f4220ab6cfe.png">

Did you download this zip file?

I tried but cannot reproduce this on my Pixel 2

<img width="494" alt="Screen Shot 2021-08-14 at 22 42 30" src="https://user-images.githubusercontent.com/54793/129448204-f71351b6-3002-4d80-bf3f-ed62f37c6818.png">

**Comment by Kita2345** [comment]
I can't reproduce this issue again, issue resolved itself

Pada tanggal Sab, 14 Agu 2021 20.44, Julian Chu ***@***.***>
menulis:

**Comment by Kita2345** [comment]
but why the file only downloaded about 9.6MB instead of 30Mb

**Comment by walkingice** [comment]
According to the crash log from firebase, I saw same crash from other device. maybe this issue is caused by race condition. I am still thinking how to reproduce it.

Maybe I will create a quick workaround to prevent crash, at least.

**Comment by walkingice** [comment]
This is a similar crash log on `Android 7.1.2 Pixel XL`

```
Fatal Exception: java.lang.IllegalArgumentException: syntax error, expected column name
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
       at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
       at android.content.ContentResolver.query(ContentResolver.java:532)
       at android.content.ContentResolver.query(ContentResolver.java:474)
       at android.app.DownloadManager$Query.runQuery(DownloadManager.java:947)
       at android.app.DownloadManager.query(DownloadManager.java:1055)
       at org.mozilla.rocket.download.data.AndroidDownloadManagerDataSource$getDownloadingItems$2.invokeSuspend(AndroidDownloadManagerDataSource.kt:133)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

DatabaseUtils throws an Exception at this line, because there was already an exception in `Parcel`
https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-7.1.2_r36/core/java/android/database/DatabaseUtils.java#165

The `Parcel` was created, transacted, the be verified at this line.
https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-7.1.2_r36/core/java/android/content/ContentProviderNative.java#421
It seems the SQL query statement that be sent to `mRemote` is wrong. ( I guess the SQL query statement is parsed then throw exception at this line: https://android.googlesource.com/platform/packages/providers/DownloadProvider/+/refs/tags/android-7.1.2_r36/src/com/android/providers/downloads/Helpers.java#632)

The SQL query statement was generated by `DownloadManager`
https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-7.1.2_r36/core/java/android/app/DownloadManager.java#902

Still trying hard to figure out how to generate a problematic SQL query statement  :-/
