### ISSUE TITLE
[BUG]  AndroidDownloadManagerDataSource.kt line 173

### ISSUE THREAD

**Issue by walkingice** [RocketScientists/Rocket#78]
```
Fatal Exception: java.lang.IllegalArgumentException: syntax error, expected column name
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:167)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
       at android.content.ContentProviderProxy.query(ContentProviderNative.java:420)
       at android.content.ContentResolver.query(ContentResolver.java:478)
       at android.content.ContentResolver.query(ContentResolver.java:422)
       at android.app.DownloadManager$Query.runQuery(DownloadManager.java:904)
       at android.app.DownloadManager.query(DownloadManager.java:1010)
       at org.mozilla.rocket.download.data.AndroidDownloadManagerDataSource$getDownloadingItems$2.invokeSuspend(AndroidDownloadManagerDataSource.kt:173)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by walkingice** [comment]
Left a comment in https://github.com/RocketScientists/Rocket/issues/57#issuecomment-967787446

I am still not sure whether above two Exceptions are same root cause or not.

The second crash exception provides SQL query statement, and this part looks weird to me

```
WHERE ((uid=10345 OR otheruid=10345)) AND (() AND status='192' AND deleted != '1') ORDER BY lastmod DESC
```
this
```
(() AND status='192' AND deleted != '1') 
```

the SQL query statement is supposed generated by DownloadManager
https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-7.1.2_r36/core/java/android/app/DownloadManager.java#902
I am still not sure how to generate the empty `()`

The second crash mostly happened on Samsung Galaxy series devices(Galaxy J7 Pro, Galaxy M01 Core...etc), and only one case on `KFAUWI`. Perhaps there are some modification in Samsung's code base.

I am still don't know how to reproduce neither the root case. If I could guess, I will guess two exception crashes have same root cause, and it might relates to race condition.

**Comment by walkingice** [comment]
I just reproduced this by using AMS device farm. By using the device `Samsung Galaxy A71` I got a crash log

```
12-08 08:58:51.517 23636  9873 E DatabaseUtils: android.database.sqlite.SQLiteException: near ")": syntax error (code 1 SQLITE_ERROR[1]): , while compiling: SELECT _id AS _id, _data AS local_filename, mediaprovider_uri, destination, title, description, uri, status, hint, mimetype AS media_type, total_bytes AS total_size, lastmod AS last_modified_timestamp, current_bytes AS bytes_so_far, allow_write, notificationpackage, dd_primaryMimeType, dd_fileName, dd_vendor, dd_description, dd_contentSize, dd_objUrl, dd_majorVersion, range_start, range_end, range_first_end, 'placeholder' AS local_uri, 'placeholder' AS reason FROM downloads WHERE ((uid=10452 OR otheruid=10452)) AND (() AND status='192' AND deleted != '1') ORDER BY lastmod DESC
12-08 08:58:51.517 23636  9873 E DatabaseUtils: ⋮.......at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
12-08 08:58:51.517 23636  9873 E DatabaseUtils: ⋮.......at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1463)   
12-08 08:58:51.517 23636  9873 E DatabaseUtils: ⋮.......at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:901)                        
12-08 08:58:51.517 23636  9873 E DatabaseUtils: ⋮.......at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)                                                                                                                 
12-08 08:58:51.517 23636  9873 E DatabaseUtils: ⋮.......at android.database.sqlite.SQLiteDatabase.validateSql(SQLiteDatabase.java:2462)                                              
12-08 08:58:51.517 23636  9873 E DatabaseUtils: ⋮.......at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:573)                                             
12-08 08:58:51.517 23636  9873 E DatabaseUtils: ⋮.......at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:463)                                                  
12-08 08:58:51.517 23636  9873 E DatabaseUtils: ⋮.......at com.android.providers.downloads.DownloadProvider.query(DownloadProvider.java:1489)                               
12-08 08:58:51.517 23636  9873 E DatabaseUtils: ⋮.......at android.content.ContentProvider.query(ContentProvider.java:1420)                        
12-08 08:58:51.517 23636  9873 E DatabaseUtils: ⋮.......at android.content.ContentProvider.query(ContentProvider.java:1516)                                                
12-08 08:58:51.517 23636  9873 E DatabaseUtils: ⋮.......at android.content.ContentProvider$Transport.query(ContentProvider.java:278)
12-08 08:58:51.517 23636  9873 E DatabaseUtils: ⋮.......at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:106)
12-08 08:58:51.517 23636  9873 E DatabaseUtils: ⋮.......at android.os.Binder.execTransactInternal(Binder.java:1190)                              
12-08 08:58:51.517 23636  9873 E DatabaseUtils: ⋮.......at android.os.Binder.execTransact(Binder.java:1159)              
12-08 08:58:51.519 31888 17375 E getDownloadingItems: runningIds: [J@5f7ad01, exception: android.database.sqlite.SQLiteException: near ")": syntax error (code 1 SQLITE_ERROR[1]): , while compiling: SELECT _id AS _id, _data AS local_filename, mediaprovider_uri, destination, title, description, uri, status, hint, mimetype AS media_type, total_bytes AS total_size, lastmod AS last_modified_timestamp, current_bytes AS bytes_so_far, allow_write, notificationpackage, dd_primaryMimeType, dd_fileName, dd_vendor, dd_description, dd_contentSize, dd_objUrl, dd_majorVersion, range_start, range_end, range_first_end, 'placeholder' AS local_uri, 'placeholder' AS reason FROM downloads WHERE ((uid=10452 OR otheruid=10452)) AND (() AND status='192' AND deleted != '1') ORDER BY lastmod DESC
```

Before this crash happened, I noticed a line

```
12-08 08:58:39.106 23636 25784 W DownloadManager: Path appears to be invalid: /storage/emulated/0/Download/5MB.zip 
```

It seems DownloadManager cannot handle the path correctly. I think its root cause is same as #86
