### ISSUE TITLE
[BUG] Fatal Exception: java.lang.IllegalStateException: Fragment FirstrunFragment not attached to a context.

### ISSUE THREAD

**Issue by walkingice** [RocketScientists/Rocket#83]
```
Fatal Exception: java.lang.IllegalStateException: Fragment FirstrunFragment ...... not attached to a context.
       at androidx.fragment.app.Fragment.requireContext(Fragment.java:900)
       at androidx.fragment.app.Fragment.getResources(Fragment.java:964)
       at androidx.fragment.app.Fragment.getString(Fragment.java:986)
       at org.mozilla.rocket.firstrun.FirstrunFragment.showAnimation$lambda-7$lambda-6(FirstrunFragment.kt:167)
       at org.mozilla.rocket.firstrun.FirstrunFragment.$r8$lambda$aCtrB-JJRB22Aciq0PG37CRSflw(FirstrunFragment.kt)
       at org.mozilla.rocket.firstrun.FirstrunFragment$$ExternalSyntheticLambda1.onAnimationUpdate()
       at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1350)
       at android.animation.ValueAnimator.animateBasedOnTime(ValueAnimator.java:1262)
       at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1310)
       at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
       at android.animation.AnimationHandler.-wrap2(AnimationHandler.java)
       at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:903)
       at android.view.Choreographer.doCallbacks(Choreographer.java:717)
       at android.view.Choreographer.doFrame(Choreographer.java:630)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:891)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:186)
       at android.app.ActivityThread.main(ActivityThread.java:6513)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:804)
```

**Comment by walkingice** [comment]
The crash occurs because the ViewBinding is captured in a Animation callback function. It is be called after Fragment detached.
