### ISSUE TITLE
[BUG]  Fatal Exception: java.lang.SecurityException Unsupported path /storage/emulated/0/Download

### ISSUE THREAD

**Issue by walkingice** [RocketScientists/Rocket#86]
```
Fatal Exception: java.lang.SecurityException: Unsupported path /storage/emulated/0/Download
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
       at android.os.Parcel.createException(Parcel.java:2357)
       at android.os.Parcel.readException(Parcel.java:2340)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:250)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:189)
       at android.content.ContentProviderProxy.insert(ContentProviderNative.java:549)
       at android.content.ContentResolver.insert(ContentResolver.java:2151)
       at android.content.ContentResolver.insert(ContentResolver.java:2113)
       at android.app.DownloadManager.enqueue(DownloadManager.java:1183)
       at org.mozilla.rocket.download.data.AndroidDownloadManagerDataSource$enqueue$2.invokeSuspend(AndroidDownloadManagerDataSource.kt:64)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

according to crash log, this crash happens mostly on Android 11. and some are on Android 10. I tried using Pixel 2 + Android 11 stock rom, but I cannot reproduce this issue, even if I removed `requestLegacyExternalStorage` from AndroidManifest.xml.

**Comment by walkingice** [comment]
https://github.com/RocketScientists/Rocket/blob/3f0bb834b418b949bb9f198dc5ec0a06c495babc/app/src/main/java/org/mozilla/rocket/download/data/AndroidDownloadManagerDataSource.kt#L61

In this line we use `setDestinationInExternalPublicDir` to download files to `/sdcard/Downlaod` , and it seems not working well on some specific devices.(most of Samsung devices).

Maybe we have to rewrite the download component to
1. download file to app specific directory
2. move downloaded file to `/sdcard/Download`

It is not a simple task, sigh.....
